Repository DESCARAVAGE/devinity, pull requests merged in 2022-06, with the labels that each got.

#2 ajout de bootstrap et de la route home / Controller
  assets/app.js
  package.json
  src/Controller/HomeController.php
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#3 S01HNC_Variable
  assets/styles/ variables.css
Labels: Review needed, Reviewed

#5 S01HNC_Variables
  assets/styles/ variables.css
Labels: Review needed, Reviewed

#7 Create entities
  migrations/Version20220629234651.php
  migrations/Version20220629235054.php
  migrations/Version20220629235245.php
  migrations/Version20220629235629.php
  migrations/Version20220630000920.php
  src/Controller/.gitignore
  src/Controller/HomeController.php
  src/Entity/Idea.php
  src/Entity/Project.php
  src/Entity/Report.php
  src/Entity/Status.php
  src/Entity/User.php
  src/Repository/IdeaRepository.php
  src/Repository/ProjectRepository.php
  src/Repository/ReportRepository.php
  src/Repository/StatusRepository.php
  src/Repository/UserRepository.php
Labels: Correction done, Review needed

#8 S01HNC_Style
  assets/styles/app.scss
  assets/styles/navbar.scss
  src/Controller/HomeController.php
  templates/components/_navbar.html.twig
Labels: Conflicts Resolved

#9 FIX_Navbar
  templates/components/_navbar.html.twig
Labels: Review needed

#10 S01HNC_Button
  assets/styles/app.scss
  templates/home/index.html.twig
Labels: Review needed

#13 add favicon
  assets/app.js
  assets/images/logo.png
  templates/base.html.twig
  webpack.config.js
Labels: Review needed

#14 Style_Nav
  assets/styles/app.scss
  assets/styles/navbar.scss
  templates/components/_navbar.html.twig
Labels: Review needed

#16 fix user
  migrations/Version20220630090928.php
Labels: Review needed

#17 fix
  src/Controller/HomeController.php
Labels: Review needed

#18 Dashboard
  .phpcs-cache
  assets/styles/dashboard.scss
  src/Controller/DashboardController.php
  templates/base.html.twig
  templates/components/_navbar.html.twig
  templates/dashboard/index.html.twig
  templates/dashboard/show_idea.html.twig
  templates/dashboard/show_project.html copy.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Correction done, Reviewed

#19 Test_animation
  .gitignore
  assets/styles/app.scss
  assets/styles/navbar.scss
  templates/home/index.html.twig
Labels: Reviewed

#20 fix
  config/packages/security.yaml
  config/routes.yaml
  migrations/Version20220630125405.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  templates/login/index.html.twig
Labels: Review needed

#22 Home content
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Reviewed

#23 fixed names
  src/Entity/Project.php
  src/Entity/User.php
Labels: Reviewed

#26 added lists
  src/Controller/HomeController.php
  src/DataFixtures/UserFixtures.php
  templates/home/index.html.twig
Labels: Reviewed

#29 Fix entities
  assets/styles/app.scss
  templates/components/_navbar.html.twig
  templates/dashboard/index.html.twig
Labels: Correction done, Reviewed

#30 finished projectPage
  assets/styles/app.scss
  src/Controller/ProjectController.php
  src/DataFixtures/ReportFixtures.php
  templates/project/index.html.twig
Labels: Review needed

#31 fixed title
  templates/project/index.html.twig
Labels: Review needed

#32 add ideas and search
  assets/styles/app.scss
  config/packages/twig.yaml
  src/Controller/HomeController.php
  src/Controller/IdeaController.php
  src/Entity/Project.php
  src/Form/IdeaType.php
  src/Form/SearchProjectType.php
  src/Repository/IdeaRepository.php
  templates/components/_navbar.html.twig
  templates/dashboard/index.html.twig
  templates/home/index.html.twig
  templates/idea/_delete_form.html.twig
  templates/idea/_form.html.twig
  templates/idea/edit.html.twig
  templates/idea/index.html.twig
  templates/idea/new.html.twig
  templates/idea/show.html.twig
Labels: Reviewed

#33 finished add crud for report
  src/Controller/ReportController.php
  src/Form/ReportType.php
  templates/project/index.html.twig
  templates/report/_form.html.twig
  templates/report/edit.html.twig
  templates/report/new.html.twig
  templates/report/show.html.twig
Labels: Review needed
